version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service/server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - STATS_DB_USER=ewm_stats_db
      - STATS_DB_PASSWORD=ewm_stats_db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=ewm_stats_db
      - POSTGRES_PASSWORD=ewm_stats_db

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
    - ewm-db
    environment:
      - EWM_DB_URL=jdbc:postgresql://ewm-db:5432/ewm_service_db
      - EWM_DB_USER=ewm
      - EWM_DB_PASSWORD=ewm
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=ewm
        - POSTGRES_PASSWORD=ewm
